### PR TITLE
Upgrade to frontools Version 1.4.2

### PR DESCRIPTION
**Pull request by MattLishman**
#  Frontools version 1.4.2

This merges in frontools version 1.4.2 with our version.

This:

- Adds Babel transpiling
- Adds Code improvements
- Removes unneeded tasks
- Preserves our additions

### CODE REVIEW

**Comment by ghost** [comment]
A couple of points we'll need to address/bear in mind:

1. The `release` task has been deprecated meaning this is a breaking change between 1.3.0 -> 1.4.2.
2. There's deprecation warnings for the config in stylelint.
3. When upgrading node_modules needs to be wiped and reinstalled locally.

It doesn't look like the deploy task is a replacement for `release`, it doesn't seem to build the JavaScript (run Babel) or process the SCSS.

**Review by ghost — CHANGES_REQUESTED** [review]
Declining this to prevent any confusion whilst we investigate further.

**Comment by MattLishman** [comment]
@jakestubbz I think the styles task has just been removed from deploy for now, although it looks like it's coming back in a later release (https://github.com/SnowdogApps/magento2-frontools/issues/25).

If we want to add styles and babel we can just do 
`gulp deploy --prod && gulp babel && gulp styles --prod`

**Comment by MattLishman** [comment]
Or we could always just add our own task which runs all these. But I imagine this just needs updating in a file somewhere that handles deployments.

**Comment by ghost** [comment]
@rhodimus: I haven't had chance to look over this again - if you get chance next week can you take a look?

**Pull request closed without merging**
